[project]
name = "lab1-mlops-homework"
version = "0.1.0"
description = "Sentyment wiadomosci"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "clean-text>=0.7.1",
    "fastapi>=0.135.3",
    "joblib>=1.5.3",
    "pre-commit>=4.5.1",
    "scikit-learn==1.7.2",
    "sentence-transformers>=5.3.0",
    "torch>=2.11.0",
    "uvicorn>=0.42.0",
]



[project.optional-dependencies]
prod = [
    "scikit-learn",
    "clean-text",
    "joblib",
    "torch",
    "sentence-transformers",
]
dev = [
    "ruff",
    "mypy",
]
test = [
    "pytest",
]
